//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public decimal pvp { get; set; }
        public int stock { get; set; }
        public string categoria { get; set; }
        public Nullable<System.DateTime> fecha_elaboracion { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public string descripcion { get; set; }
    }
}
